site_name: My Docs
nav: 
  - 'index.md'
  - 'changelog.md'
  - 'reference.md'
  - 'license.md'
theme:  
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle: 
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
